name: Devlog — append on PR merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  append-devlog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build devlog entry and append
        uses: actions/github-script@v7
        with:
          script: |
            const tz = 'America/Phoenix';
            const now = new Date();
            const parts = new Intl.DateTimeFormat('en-US', { timeZone: tz, year:'numeric', month:'2-digit', day:'2-digit' }).formatToParts(now);
            const y = parts.find(p=>p.type==='year').value;
            const m = parts.find(p=>p.type==='month').value;
            const d = parts.find(p=>p.type==='day').value;
            const dateStr = `${y}-${m}-${d}`;

            const pr = context.payload.pull_request;
            const title = pr.title || 'Untitled PR';
            const number = pr.number;
            const url = pr.html_url;
            const branch = pr.head && pr.head.ref ? pr.head.ref : '';

            const body = pr.body || '';
            const START = '<!-- DEVLOG_START -->';
            const END = '<!-- DEVLOG_END -->';
            let entryBody = '';
            if (body.includes(START) && body.includes(END)) {
              entryBody = body.split(START)[1].split(END)[0].trim();
            } else {
              entryBody = `Merged PR #${number} — ${title}`;
            }

            const fs = require('fs');
            const path = require('path');
            const devlogDir = path.join(process.cwd(), 'docs', 'devlog');
            const filePath = path.join(devlogDir, `${dateStr}.md`);
            if (!fs.existsSync(devlogDir)) fs.mkdirSync(devlogDir, { recursive: true });

            let content = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
            if (!content.startsWith(`# Devlog — ${dateStr}`)) {
              content = `# Devlog — ${dateStr}\n\n` + content;
            }

            const entry = [
              `## ${title}`,
              ``,
              `${entryBody}`,
              ``,
              `- PR: #${number} (${url})`,
              branch ? `- Branch: ${branch}` : ``,
              ``
            ].filter(Boolean).join('\n');

            fs.writeFileSync(filePath, content + entry, 'utf8');
      - name: Commit devlog entry
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/devlog/*
          git commit -m "docs(devlog): auto-append PR #${{ github.event.pull_request.number }} [skip ci]" || echo "No changes"
          git push