name: Docs — markdownlint
on:
  push:
    paths:
      - "**/*.md"
      - ".github/workflows/md-lint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/md-lint.yml"
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run markdownlint
        run: |
          npx --yes markdownlint-cli "**/*.md" --ignore node_modules --ignore "lychee/**"
