name: Quality checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Offline link check to avoid network flakiness; ignore docs/ snippets
      - name: Link check (offline)
        uses: lycheeverse/lychee-action@v1
        with:
          args: --offline --no-progress --verbose --exclude-path "./docs/*" ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: HTML validate (uses .htmlvalidate.json if present)
        run: npx --yes html-validate "**/*.html"

      - name: Markdown lint (uses .markdownlint.yaml if present)
        run: npx --yes markdownlint-cli "**/*.md" --ignore node_modules
